phases:
- phase: Linux
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache

  steps:
  - checkout: self
    clean: true

  - bash: |
      cd $(Agent.WorkFolder)
      git clone https://github.com/juj/emsdk.git
      cd emsdk
      ./emsdk install latest
      ./emsdk activate latest
    displayName: 'Run make'

  - bash: |
      source $(Agent.WorkFolder)/emsdk/emsdk_env.sh
      npm -g install typescript
      npm install
      make 
    displayName: 'Run make'
